export const customBangs = [
  {
    c: "AI",
    d: "chatgpt.com",
    r: 0,
    s: "ChatGPT",
    sc: "AI",
    t: "aic", // meaning "AI Chat"
    u: "https://chatgpt.com?q={{{s}}}",
  },
  {
    c: "AI",
    d: "chatgpt.com",
    r: 0,
    s: "ChatGPT",
    sc: "AI",
    t: "gpt",
    u: "https://chatgpt.com?q={{{s}}}",
  },
  {
    c: "AI",
    d: "chatgpt.com",
    r: 0,
    s: "ChatGPT",
    sc: "AI",
    t: "ai",
    u: "https://chatgpt.com?q={{{s}}}",
  },
  {
    c: "Perplexity",
    d: "www.perplexity.ai",
    r: 0,
    s: "Perplexity",
    sc: "AI",
    t: "ppx",
    u: "https://www.perplexity.ai/search?s=o&q={{{s}}}",
  },
  {
    c: "DuckDuckGo Bangs",
    d: "www.duckduckgo.com",
    r: 0,
    s: "DuckDuckGo Bangs",
    sc: "",
    t: "bang",
    u: "https://duckduckgo.com/bangs?q={{{s}}}",
  },
  {
    c: "Online Services",
    d: "www.google.com",
    r: 0,
    s: "Google (Clean)",
    sc: "Google",
    t: "gc",
    u: "https://www.google.com/search?udm=14&q={{{s}}}",
  },
  {
    c: "Online Services",
    d: "www.twitter.com",
    r: 9964,
    s: "Twitter",
    sc: "Social",
    t: "twt",
    u: "https://twitter.com/search?q={{{s}}}",
  },
  {
    c: "Tech",
    d: "grep.app",
    r: 0,
    s: "Grep.app",
    sc: "Programming",
    t: "grep",
    u: "https://grep.app/search?q={{{s}}}",
  },
  {
    c: "Shopping",
    d: "facebook.com",
    r: 0,
    s: "Facebook Marketplace",
    sc: "Online (marketplace)",
    t: "fbm",
    u: "https://www.facebook.com/marketplace/search?query={{{s}}}",
  },
  // Google Maps changed their URL structure, so the original bang is currently broken.
  {
    c: "Online Services",
    d: "google.com",
    r: 0,
    s: "Google Maps",
    sc: "Maps",
    t: "gm",
    u: "https://google.com/maps/search/{{{s}}}",
  },
  {
    c: "Tech",
    d: "npmx",
    r: 147,
    s: "npmx",
    sc: "Programming",
    t: "npmx",
    u: "https://npmx.dev/search?q={{{s}}}",
  },
];
